react_native_path = File.expand_path('../node_modules/react-native', __dir__)
require File.join(react_native_path, 'scripts/react_native_pods')

platform :ios, '16.1'

target 'LxMusic' do
  config = use_native_modules!

  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.1'
      end
    end
  end
end
